-- ============================================================
-- Shiny Tracker — Supabase Schema
-- Run this in your Supabase SQL Editor to set up the database.
-- ============================================================

create table if not exists public.hunts (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now() not null,
  updated_at     timestamptz default now() not null,

  -- Trainer
  username       text not null,

  -- Pokémon info (cached from PokéAPI)
  pokemon_name   text not null,          -- e.g. "charizard"
  display_name   text not null,          -- e.g. "Charizard"
  pokemon_id     int,                    -- Pokédex number
  types          text[],                 -- e.g. ARRAY['fire','flying']
  sprite         text,                   -- normal sprite URL
  shiny_sprite   text,                   -- shiny sprite URL
  official_art   text,                   -- official art URL
  shiny_official_art text,               -- shiny official art URL
  genus          text,                   -- e.g. "Flame Pokémon"

  -- Hunt details
  method         text not null default 'random',
  method_label   text,
  game           text not null default 'sv',
  game_label     text,
  attempts       int not null default 0,
  status         text not null default 'hunting' check (status in ('hunting', 'caught')),
  shiny_charm    boolean not null default false,
  base_rate      int,                    -- 1/N denominator at time of logging
  caught_date    date,
  notes          text
);

-- Index for fast per-trainer queries
create index if not exists hunts_username_idx on public.hunts (username);
create index if not exists hunts_status_idx   on public.hunts (status);

-- Auto-update updated_at
create or replace function public.handle_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_updated_at on public.hunts;
create trigger set_updated_at
  before update on public.hunts
  for each row execute procedure public.handle_updated_at();

-- ============================================================
-- Row Level Security (RLS)
-- ============================================================
-- By default the app uses the anon key with RLS disabled for
-- simplicity (username scoping in JS). For production, enable
-- Supabase Auth and swap these policies for auth.uid() checks.

alter table public.hunts enable row level security;

-- Public read/write scoped by username (no auth required)
-- Replace with proper auth policies for production.
create policy "Allow all for matching username"
  on public.hunts
  for all
  using (true)
  with check (true);

-- ============================================================
-- Realtime
-- ============================================================
alter publication supabase_realtime add table public.hunts;
